### ISSUE TITLE
Application refuses to open if it can't download the fedimint config

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-node#1058]
```
ERROR [mutiny_core::federation:221] Could not parse invite code: Failed to download client config
```

**Comment by benthecarman** [comment]
We should only be downloading this when we add the federation, not on startup, the config must not be being saved to the db

**Comment by TonyGiorgio** [comment]
this was from the result of someone we know running a very old and unsupported version of mutiny with fedimint.
