### ISSUE TITLE
Error: Failed to make a request to the LSP.

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-node#1065]
This should not freeze up on startup when the LSP is down.

**Comment by benthecarman** [comment]
I cannot reproduce this. We only block startup with a request to the LSP if we don't have its connection info from a previous run. Even on a fresh wallet when I set the LSP url to `example.com` it still works.

**Comment by TonyGiorgio** [comment]
I can promise you that this is indeed an issue when the LSP is undergoing maintenance.
