### ISSUE TITLE
Blind Auth Follow Ups

### ISSUE THREAD

**Issue by benthecarman** [MutinyWallet/mutiny-node#1079]
- [x] Check for new tokens after mutiny+ subscription
- [x] Proper DM listening handling
- [ ] save our lightning address in storage

follow up: 
Add change federation functionality

**Comment by futurepaul** [comment]
is there a way I can get a better error for if a name is already taken?

<img width="250" alt="Screenshot 2024-03-26 at 4 32 01 PM" src="https://github.com/MutinyWallet/mutiny-node/assets/543668/6fa8fed5-79c0-45df-b557-caf3f6a5e3f6">

**Comment by TonyGiorgio** [comment]
The check_name API call should be called first, and it returns a boolean value.

**Comment by futurepaul** [comment]
> The check_name API call should be called first, and it returns a boolean value.

ah nice

**Comment by TonyGiorgio** [comment]
> save our lightning address in storage

I've been thinking about how to do this. There's the naive approach of storing to local storage what the LN address should be. But what I'm thinking is that it can be a query to the hermes server. 

We already know what the deterministic nostr pubkey will be for the user, so it can create a signed message from that nostr pubkey to something like `/check-address` which returns the federation id and the name for the user. That's the source of truth afterall. Anything we did locally would need to have some sort of cross check against the server. 

Then from there, we can have federation changes happen the same way. We can see if the user's defined federation is different than the one stored on hermes. If so, then it creates a signed nostr message and then makes a request to `/change-federation` with the invite code it wants to change to. 

Lastly (for a follow up some other day), to change names it can follow the same federation change flow, but for `/change-name` and it maybe just gets an invoice back that it has to pay to change the name?

**Comment by benthecarman** [comment]
That makes sense to me. I think we should try to do some local caching so we don't need to hit the server every time we boot up

**Comment by TonyGiorgio** [comment]
What kind of caching do you think would be best here? 

We can do something like a daily cache? Weekly? 

Store it in local storage but not needed to be remotely backed up? If it's missing in local storage then it fetches remotely. 

My main worry is from switching devices and not having the latest state if one of the devices changes federations or does the name change.

**Comment by benthecarman** [comment]
If we just store it in VSS then it should be fine

**Comment by TonyGiorgio** [comment]
> If we just store it in VSS then it should be fine

I want to avoid storing in VSS just to store in VSS.
