### ISSUE TITLE
`create_bip21` returns error if `create_lightning_invoice` returns an error

### ISSUE THREAD

**Issue by DanGould** [MutinyWallet/mutiny-node#1113]
If a lightning invoice can't be fetched, Mutiny is still be able to create a bip21 with an amount and a label, no need to fail the whole operation.

If address creation fails, it makes sense to error, but that should be basically impossible.

Working on a fix.

**Comment by benthecarman** [comment]
This is by design so if lightning fails we can display the error then just call get_address manually afterwards

**Comment by DanGould** [comment]
I understand that but I think a design like this could let you return an error to display without killing the whole Bip21 creation

```rs
pub struct MutinyBip21RawMaterials {
    pub address: Address,
    pub invoice: Option<Result<Bolt11Invoice, MutinyError>>,
    pub btc_amount: Option<String>,
    pub labels: Vec<String>,
}
```

And then display an invoice error if it's `Some(Err)`.

Once you add payjoin or another fallable function in create_bip21 there become even more ways to fail e.g.

```rs
pub struct MutinyBip21RawMaterials {
    pub address: Address,
    pub invoice: Option<Result<Bolt11Invoice, MutinyError>>,
    pub pj: Option<Result<PjParams, MutinyError>>,
    pub btc_amount: Option<String>,
    pub labels: Vec<String>,
}
```

imo using `MutinyError` for each error instance makes handling more difficult too but that's beyond the scope of this individual concern.
