### ISSUE TITLE
Error parsing federation config

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-node#1183]
```
Error parsing meta config: error decoding response body: invalid type: boolean `false`, expected a string at line 530 column 1
```

**Comment by benthecarman** [comment]
We should probably just return the raw json to the front end instead of trying to parse every value ourselves

**Comment by TonyGiorgio** [comment]
So the frontend can run into the same exact issues parsing configs as we do? No thanks.

**Comment by benthecarman** [comment]
Javascript won't fail to parse the whole thing if one type is wrong

**Comment by TonyGiorgio** [comment]
We're very capable of using a serializer that wouldn't do that.
