### ISSUE TITLE
paying a lightning node from federation fails

### ISSUE THREAD

**Issue by vincenzopalazzo** [MutinyWallet/mutiny-node#1184]
I am doing some tests with my mutinywallet with federations and if I send between two wallets in the same federation all is fine, but the problem is when I want to send the amount on my core lightning node.

This is the error that the wallet return 

![signal-2024-05-13-090706](https://github.com/MutinyWallet/mutiny-node/assets/17150045/02979a85-e019-43d9-8338-8f28c21275c0)

This is the invoice: `lnbc100n1pnyr0gvdqqpp5pqun46arwmwfvpypf3v7lnq8vnpt5yfawvn2aeshn8zpsvpllxfqsp5jjdctxk4u5scl4q9saw0408m0szpelcx7ewusygjdu7qz9hdw04s9qrsgqcqpjnp4qwd96x2u6rgg5mjvrdh5cs989pm3tyh869rk53u2mz9hnux85par6xqyz5vqrzjqte649ct9zh8ecjylt7w3a5d9mvpdchtgsgecu22yycumagdx3uukqqqqqqqqqqqqyqqqqqqqqqqqqqqrc6fx2xy4ala6u0kxrj5fsx6vpmq0kd5l2usej6ywdh52jax2jjlms6x5zjf748dkcgggq4gymz288ngdd2ufshnafqza96wa8rcm8cscq0um0mx` and I have 2.118 sats on my wallet, so I should be able to pay it right?

 This is the log file  [mutiny-logs.txt](https://github.com/MutinyWallet/mutiny-node/files/15290877/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Insufficient balance: requested 2139170 msat but only 2119000 msat available

**Comment by vincenzopalazzo** [comment]
>Insufficient balance: requested 2139170 msat but only 2119000 msat available

I see while looking at the log but there is anyway from the wallet point of view to show this error? or just to alert the user in some way before making the payment?
