### ISSUE TITLE
Logging has a bunch of `<empty string> <empty string> <empty string>`s

### ISSUE THREAD

**Issue by benthecarman** [MutinyWallet/mutiny-node#1201]
my logs are filled with this from the update
![image](https://github.com/MutinyWallet/mutiny-node/assets/15256660/bf70db0e-90ca-448d-9a3e-1e8a8dc3003e)

**Comment by TonyGiorgio** [comment]
Can't reproduce. Make sure you're up to date.

**Comment by benthecarman** [comment]
Still happens to me on master of both, seems to be only in firefox though
