### ISSUE TITLE
On chain balance disappeared

### ISSUE THREAD

**Issue by Cashstachestashcache** [MutinyWallet/mutiny-node#1229]
Zapping out/transferring ecash from freedom one to another wallet and midway through I closed the app and refreshed but now my onchain is gone! 

I resynced a couple times but it just said 0 
[mutiny.txt](https://github.com/user-attachments/files/15979348/mutiny.txt)

**Comment by TonyGiorgio** [comment]
If a resync is not working then you can go through the recovery flow here: https://github.com/MutinyWallet/mutiny-web/wiki/Recovery#on-chain

**Comment by Cashstachestashcache** [comment]
Thank you
