### ISSUE TITLE
panicked at library/std/src/sys/wasm/../unsupported/thread.rs:26:9: can't sleep

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-node#1231]
Something is calling `thread::sleep`: 

https://sen.mutinywallet.com/organizations/sentry/issues/1715/events/80bc66927ce04d27811e59bb3046c7bd/events/

**Comment by benthecarman** [comment]
https://github.com/fedimint/fedimint/pull/5557
