### ISSUE TITLE
Issues retrieving sats from multiple force closes

### ISSUE THREAD

**Issue by bedair81** [MutinyWallet/mutiny-node#1240]
Hi!

A week or so ago I force closed some channels and the existing tx was set at 3 sat/vb so I was just waiting for it to be confirmed. I ended up accelerating the tx yesterday and getting it confirmed but this only let to a small amount of the total sats im waiting for to be accepted. Any help would be appreciated and the logs are attached. Thanks!
[mutiny-logs.txt](https://github.com/user-attachments/files/16189066/mutiny-logs.txt)

**Comment by TonyGiorgio** [comment]
Forced closed channels take multiple days to resolve after confirmed.

**Comment by bedair81** [comment]
In the log file attached towards the bottom if you have a look there are a bunch of tx's the wallet is trying to broadcast and failing, not sure what the error message is. Is that something I should be looking into or will that not affect the sats settling after the force closes?

**Comment by benthecarman** [comment]
just wait a few days

**Comment by bedair81** [comment]
Thanks!
