### ISSUE TITLE
Reproduce and investigate force closure issues

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-node#196]
Happened to me once which was with an outdated state, happened to ben once but not sure if he got his funds back on chain. Need to make sure this is well tested.

**Comment by TonyGiorgio** [comment]
Would you consider this resolved now @benthecarman ?

**Comment by benthecarman** [comment]
Maybe.. Probably should redeploy on reckless.mutinywallet.com and doing some real testing again

**Comment by TonyGiorgio** [comment]
Haven't had force closures in awhile
