### ISSUE TITLE
Add to Readme that you need nightly rust

### ISSUE THREAD

**Issue by benthecarman** [MutinyWallet/mutiny-node#253]

**Comment by TonyGiorgio** [comment]
is there any other kind of rust?

**Comment by TonyGiorgio** [comment]
do we care about targetting specific versions?

**Comment by benthecarman** [comment]
Someone was having trouble onboarding because they didn't have nightly rust ![image](https://user-images.githubusercontent.com/15256660/209458994-61722891-3f59-4ee9-9b28-524c5e80b27c.jpeg)
