### ISSUE TITLE
channelmanager error when closing channel about feerate disagreement

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-node#286]
![Screen Shot 2022-12-30 at 5 06 09 PM](https://user-images.githubusercontent.com/543668/210117090-c6705736-7907-415a-960e-ac3cd38fbf21.png)

tried to close a channel, it failed, I didn't look at the logs. but when I tried again a few minutes later it did close but I saw this error in the process

**Comment by TonyGiorgio** [comment]
We have refined some of the fee rate handling but this is expected. LDK will try to close a few times and then fall back to force closing if it's due to fee rate. Unfortunately testnet and signets can be unreliable when it comes to these fee rate estimates.
