### ISSUE TITLE
Failing m2m send: "failed to find route"

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-node#296]
brand new channel and node states, it's def confirmed

![Screen Shot 2023-01-02 at 3 53 57 PM](https://user-images.githubusercontent.com/543668/210280381-c0dd97a4-e690-4a92-b95f-715757a1c51f.png)

**Comment by TonyGiorgio** [comment]
Do you remember how much you were trying to send? Says `outbound_htlc_maximum_msat` is 5000000 msats, so that's only 5k sats.

**Comment by TonyGiorgio** [comment]
Closing. Need more detailed logs and context. If it happens again when it was expected, open up a ticket.
