### ISSUE TITLE
Announce our node on gossip

### ISSUE THREAD

**Issue by benthecarman** [MutinyWallet/mutiny-node#349]

**Comment by TonyGiorgio** [comment]
> Would the node announcment come from
> 
> https://github.com/MutinyWallet/mutiny-node/blob/58f7e473ba171f781dea37d98315c0ce838e4ed5/mutiny-core/src/background.rs#L252
> 
> On process peer_manager?

No, `background.rs` is almost identical to the rust-lightning version and shouldn't really be touched. I am a little unsure what the benefit of announcing mutiny wallet node gossip actually.

**Comment by bennyhodl** [comment]
> No, `background.rs` is almost identical to the rust-lightning version and shouldn't really be touched. I am a little unsure what the benefit of announcing mutiny wallet node gossip is actually.

From LDK docs

>What it's used for: if you have 1 or more public channels, you may need to announce your node and its channels >occasionally. LDK will automatically announce channels when they are created, but there are no guarantees you have >connected peers at that time or that your peers will propagate such announcements. The broader node-announcement >message is not automatically broadcast.

**Comment by TonyGiorgio** [comment]
We don't do public channels so I don't think this would do anything here.
