### ISSUE TITLE
"Failed to conduct chain access operation" error

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-node#376]
<img width="943" alt="Screenshot 2023-04-18 at 1 21 26 PM" src="https://user-images.githubusercontent.com/543668/232870001-6d70ec20-053c-4f15-b63b-2abf30b86840.png">

during a successful channel open the wallet was briefly broken on this. first refresh it was still broken, then everything worked after the second refresh and the channel was open

not a cors issue btw, I think maybe the mempool endpoint just wasn't avail yet?

**Comment by TonyGiorgio** [comment]
This seems to be resolved, not sure if it's because the endpoint is returning something now or if it is because of some additional work on the syncing. Please reopen if this is showing up for you on the latest v0.2.8.
