### ISSUE TITLE
`check_address` doesn't work for confirmed addresses?

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-node#414]
- If I call `check_address` with a fresh address it returns null.
- If I call it with an address that has been paid I get the tx info I expect.
- But once it's confirmed I get an error: `Failed to conduct chain access operation.`

**Comment by futurepaul** [comment]
This is no longer happening for me... in the same setting where it was happening. I'm confused I'll report back if this happens again.

**Comment by futurepaul** [comment]
Ah nope, happening again.

**Comment by benthecarman** [comment]
Ah I think this is something that I tried to do with bdk, we try inserting the tx but looks like this can fail if our chain tip isn't caught up. Should be an easy-ish fix

https://github.com/MutinyWallet/mutiny-node/blob/master/mutiny-core/src/nodemanager.rs#L525
