### ISSUE TITLE
Labels API improvements

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-node#493]
## Create contact

Right now create contact expects a Contact as an argument and it doesn't seem to accept an object with the optionals left out, such as `{ name: "ben", last_used: 0n }`.

What would be nice is a constructor function that takes individual arguments rather than the struct.

## Edit contact

didn't see a way to change an existing contact

## Text labels for transactions

I seem to be saving text labels correctly but they're not showing when I list txs. I do see them on invoices now though.

**Comment by futurepaul** [comment]
proof the labels are stored:

<img width="844" alt="Screenshot 2023-05-10 at 10 52 20 AM" src="https://github.com/MutinyWallet/mutiny-node/assets/543668/cff4636b-ac58-45fd-ae22-b00d9119dc3f">

<img width="753" alt="Screenshot 2023-05-10 at 10 52 55 AM" src="https://github.com/MutinyWallet/mutiny-node/assets/543668/700e2219-75e0-4662-b888-9548f1645342">

but not in the tx info:
<img width="598" alt="Screenshot 2023-05-10 at 2 09 48 PM" src="https://github.com/MutinyWallet/mutiny-node/assets/543668/3dd11a04-346d-42f1-aa2c-24bd74beaa31">

**Comment by futurepaul** [comment]
<img width="430" alt="Screenshot 2023-05-10 at 3 32 58 PM" src="https://github.com/MutinyWallet/mutiny-node/assets/543668/017faa6a-1025-4485-bf90-d5a9f7b1adc1">

**Comment by benthecarman** [comment]
After https://github.com/MutinyWallet/mutiny-node/pull/498 we'll just be missing edit contact
