### ISSUE TITLE
Force close with LSP

### ISSUE THREAD

**Issue by benthecarman** [MutinyWallet/mutiny-node#568]
Steps to reproduce:

1. Initiate swap to lightning to LSP
2. Immediately force close app after the success screen
3. Wait 10 seconds
4. Reopen app
5. Channel should be force closed

**Comment by benthecarman** [comment]
Probably a CLN bug, just documenting here

**Comment by TonyGiorgio** [comment]
The temp solution to this was to make the channel open flow wait one second before returning but a longer term fix is going to be by being reactive to the EventManager. 

https://github.com/MutinyWallet/mutiny-node/issues/594
