### ISSUE TITLE
Lightning channel open shows 0 amount upon launch

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-node#580]
0 balance for on chain and 0 balance for the activity list view for that item, until ~60s when it populates again. 

![Screenshot from 2023-06-09 14-34-03](https://github.com/MutinyWallet/mutiny-node/assets/101225832/d93002f5-b447-4fd1-9f85-f53e4b89b79f)

**Comment by benthecarman** [comment]
I think the on-chain syncing fixes fixed this
