### ISSUE TITLE
Lightning send failure not sure if it's LSP fault

### ISSUE THREAD

**Issue by futurepaul** [MutinyWallet/mutiny-node#598]
receiver:
<img width="597" alt="Screenshot 2023-06-15 at 6 15 17 PM" src="https://github.com/MutinyWallet/mutiny-node/assets/543668/5778868c-8af9-4cd9-8143-0a39d30dfb03">

sender:
<img width="591" alt="Screenshot 2023-06-15 at 6 19 24 PM" src="https://github.com/MutinyWallet/mutiny-node/assets/543668/1e88a506-9b51-4ef2-9505-95724a948f3a">

I have a node with some channels but no inbound
trying to send it 100k sats over lightning
payment times out... balance goes down temporarily and then comes back ~30 seconds later

<img width="502" alt="Screenshot 2023-06-15 at 6 18 27 PM" src="https://github.com/MutinyWallet/mutiny-node/assets/543668/1a8073f9-fd91-49d2-b44f-e6f8c64a405b">

[sender and receiver jsons.zip](https://github.com/MutinyWallet/mutiny-node/files/11763910/sender.and.receiver.jsons.zip)

**Comment by TonyGiorgio** [comment]
This is due to LDK not considering MPP payments being made when constructing other parts. Will be fixed in the next version.

-------- Original Message --------
