### ISSUE TITLE
cannot find macros and functions in scope while running `just test`

### ISSUE THREAD

**Issue by AbhinavMir** [MutinyWallet/mutiny-node#630]
The build on the new commit works perfectly, but when running the test, I run into ~1000 errors along the lines of:  `cannot find function, tuple struct or tuple variant `Ok` in this scope` and other various errors such as `cannot find macro `debug_assert` in this scope` etc etc. What am I doing wrong?

**Comment by TonyGiorgio** [comment]
Do you happy to have this particular version of rust nightly? 

https://github.com/MutinyWallet/mutiny-node#dependencies

We were having problems with one of their recent nightly changes. Also, make sure you have wasm-pack and some of the other stuff listed there. Perhaps there's another thing we have missing from this list though. 

Could you try to run these commands individually too? Just to make sure we know which one is giving you that problem. 

https://github.com/MutinyWallet/mutiny-node/blob/8c33062225992f6bd29c34763f620e894550e288/justfile#L16

**Comment by AbhinavMir** [comment]
Hi, I have the latest releases of tools, any older tools you'd suggest downgrading to to get this working? I have every other binary needed installed.

The first command seems to give me the problem. Was working just fine before I did the git pull :(

**Comment by TonyGiorgio** [comment]
You shouldn't have to downgrade any of the rust stuff but does installing an older version of it fix it? 

```
rustup toolchain install nightly-2023-04-16
```

```
rustup target add wasm32-unknown-unknown --toolchain nightly-2023-04-16
```

Maybe also this is needed too? 

```
rustup target add x86_64-unknown-linux-gnu --toolchain nightly-2023-04-16
```

**Comment by AbhinavMir** [comment]
Tried all three, still fails. I suspected it would be the last one, but no luck.

**Comment by benthecarman** [comment]
We updated so we no longer need the specific version of nightly rust, should work much easier now

**Comment by AbhinavMir** [comment]
Thanks guys, appreciate it!
