### ISSUE TITLE
Find other places we can use async RwLock 

### ISSUE THREAD

**Issue by benthecarman** [MutinyWallet/mutiny-node#925]
There's probably other places in the codebase we can do this too, would be a good followup

_Originally posted by @benthecarman in https://github.com/MutinyWallet/mutiny-node/issues/924#issuecomment-1874681808_

**Comment by TonyGiorgio** [comment]
Well, clippy warns when you're using a non async mutex over an await so we aren't doing it currently but maybe we benefit from doing that swap anyways.
