### ISSUE TITLE
Missing fedimint activity items

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-node#947]
Not sure what triggers it, never get it locally/in signet but in prod I've been missing a lot of fedimint transactions, sometimes seconds after they happen.

**Comment by benthecarman** [comment]
had a user report this happened with a nwc payment, maybe it happens when its labeled?

**Comment by ekzyis** [comment]
I was able to reliably (not always but often enough) reproduce it by zapping people using NWC. It seems to only show the latest zap in most cases. See video:


https://github.com/MutinyWallet/mutiny-node/assets/27162016/624e4e4f-4944-4a67-85ea-650be953d63c
